### ISSUE TITLE
Release for Elm 0.19

### ISSUE THREAD

**Issue by michaeljones** [zwilias/json-decode-exploration#6]
We're still happily using this in production and I've noticed that there isn't a 0.19 release yet. Could I help with that? Should I try to put together a PR?

Thanks!

**Comment by zwilias** [comment]
Cool, I'll get this upgraded! Thanks for verifying - I wasn't sure if anyway was, in fact, still using this 😄

**Comment by michaeljones** [comment]
Yeah, understandable. Perhaps kind of niche but definitely solves a problem for us that I'm really concerned about. Basically that we have a big json blob in our database and we edit it with a UI but if there is anything in the json blob that the Elm code doesn't recognise then I don't want it continuing happily along in case we lose that unrecognised information. So this has been great to detect those situations :)

**Comment by zwilias** [comment]
Published as 5.0.1!

**Comment by michaeljones** [comment]
Thanks!
